### ISSUE TITLE
Reading 'UID' 에러

### ISSUE THREAD

**Issue by ryyugang** [Jungle-Team3-Olympus/jungle-navigation-react#100]
### 🐞 Describe

- 어떤 상황 시 발생하는 에러인지 특정하지 못했음

### 📄 Logs

```shell
ERROR
Cannot read properties of undefined (reading 'uid')
TypeError: Cannot read properties of undefined (reading 'uid')
    at Socket.<anonymous> (http://localhost:3000/static/js/bundle.js:4878:33)
    at Emitter.emit (http://localhost:3000/static/js/bundle.js:299255:20)
    at Socket.emitEvent (http://localhost:3000/static/js/bundle.js:329460:16)
    at Socket.onevent (http://localhost:3000/static/js/bundle.js:329448:12)
    at Socket.onpacket (http://localhost:3000/static/js/bundle.js:329418:14)
    at Emitter.emit (http://localhost:3000/static/js/bundle.js:299255:20)
    at http://localhost:3000/static/js/bundle.js:328755:12
```

### 🌏 Environment

localhost 환경에서 목격

### 🕰️ Estimated Time of Completion

ㅠㅠ

**Comment by Digit24-dev** [comment]
에러 위치:
GameScene.js - constructor - this.socket.on("message", ...

```
     case "move":
          // console.log(data);
          const user = data.user;

          // 움직인 유저 정보만 받아와서 갱신해주기
          if (this.OPlayer[user.uid]) {
            const otherPlayer = this.OPlayer[user.uid];
            if (otherPlayer.x !== user.x || otherPlayer.y !== user.y) {
              otherPlayer.moveTo(user.x, user.y, user.direction);
              otherPlayer.setMoving(true);
            } else {
              otherPlayer.setMoving(false);
            }
          }
          break;

```
