### ISSUE TITLE
ERROR: reading 'add'

### ISSUE THREAD

**Issue by Digit24-dev** [Jungle-Team3-Olympus/jungle-navigation-react#109]
### 🐞 Describe

최초 로그인 시에 간헐적으로 발생.

### 📄 Logs

```shell
Cannot read properties of undefined (reading 'add')
TypeError: Cannot read properties of undefined (reading 'add')
    at GameScene.create_OPlayer (https://pixeller.net/static/js/bundle.js:5186:20)
    at Socket.<anonymous> (https://pixeller.net/static/js/bundle.js:4936:18)
    at Emitter.emit (https://pixeller.net/static/js/bundle.js:299544:20)
    at Socket.emitEvent (https://pixeller.net/static/js/bundle.js:329694:16)
    at Socket.onevent (https://pixeller.net/static/js/bundle.js:329682:12)
    at Socket.onpacket (https://pixeller.net/static/js/bundle.js:329652:14)
    at Emitter.emit (https://pixeller.net/static/js/bundle.js:299544:20)
    at https://pixeller.net/static/js/bundle.js:328989:12
```

### 🌏 Environment

크롬 브라우저

### 🕰️ Estimated Time of Completion

-

**Comment by ryyugang** [comment]
발생 원인 : 

- GameScene 클래스의 create_OPlayer 메서드에서 this.players가 정의되지 않았거나 undefined인 상태에서 add 메서드를 호출해서

변경 사항 : 

- this.players 초기화 
  : this.players 그룹의 초기화 시점을 명확히 하여 undefined 오류 방지

- create 메서드에서 this.players 그룹 생성 및 플레이어 추가

- syncUser 케이스에서 create_OPlayer 호출 위치 변경
  : syncUser 케이스에서 모든 유저 정보 처리 후 한 번만 create_OPlayer를 호출하도록 최적화

- create_OPlayer 메서드에서 오류 처리 개선
